/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: MushyDay (https://sketchfab.com/MushyDay)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/jellyfish-a2645d543a7246b3aad9c352407f6456
Title: Jellyfish
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Jellyfish(props) {
  const { nodes, materials } = useGLTF('src/assets/models/jellyfish.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.408}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[-0.023, 0.002, 0.252]}
            rotation={[3.132, 1.438, -Math.PI]}
            scale={1.667}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_4.geometry}
              material={materials['Jelly.cap']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_6.geometry}
              material={materials['Jelly.bud']}
              position={[0, 0.084, 0]}
              rotation={[0, -1.267, -0.262]}
              scale={1.156}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('src/assets/models/jellyfish.glb')
